/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfigForm: typeof import('./src/components/ConfigForm/ConfigForm.vue')['default']
    ConfigSearchPage: typeof import('./src/components/ConfigSearchPage/ConfigSearchPage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld/HelloWorld.vue')['default']
  }
}
