name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main # 可以根据需要修改分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # 根据你的项目需求选择合适的 Node.js 版本

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build docs
        run: pnpm run docs:build # 确保你的项目中有这个脚本

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # GitHub Pages 默认分支
          folder: packages/docs/.vitepress/dist # 构建后的文档目录
          clean: true # 清除 gh-pages 分支上的旧文件
